INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.INITIAL_COMMUNICATION_INFO
(
	UUID ,
	RESPONSIBLE_ID ,
	INITIAL_COMMUNICATION_METHOD , 
	INITIAL_COMMUNICATION_DATE , 
	CREATEDON , 
	CREATEDBY ,
	MODIFIEDON , 
	MODIFIEDBY 
)
SELECT 
	SYS_GUID() UUID,
	RESPONSIBLE_ID,
	'Paper Letter' INITIAL_COMMUNICATION_METHOD,
	INITIAL_COMMUNICATION_DATE, 
	SYSTIMESTAMP CREATEDON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATEDBY,
	SYSTIMESTAMP MODIFIEDON, 
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIEDBY	
FROM 
	(
		SELECT 
			r2.ID RESPONSIBLE_ID, 
			L.STRATEGYDATE INITIAL_COMMUNICATION_DATE, 
			RANK() OVER (PARTITION By l.responsibleid ORDER BY l.strategydate) AS rnk
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.LETTERCHANNELACTUALRESULT l 
		INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLEINDEX r2 ON L.RESPONSIBLEID = R2.RESPONSIBLEID  
	) WHERE rnk = 1