INSERT INTO COM_FINVI_OASIS_ACCOUNT_ACTIVITY_{PP_TenantName}.ACTIVITY
(
	ID, 
	TRANSACTION_ID, 
	USER_ID,
	CONTEXT, 
	CATEGORY, 
	"TYPE", 
	"DATA",
	DATA_VERSION, 
	"TIMESTAMP", 
	CREATED_ON, 
	MODIFIED_ON
)
SELECT 
	SYS_GUID()  AS ID,
    SYS_GUID()  AS TRANSACTION_ID,
    (
		SELECT IDPUSERID 
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ 
		WHERE USERNAME = 'etlmigrationuser@finvi.com'
	) AS USER_ID,
    'ACCOUNT' AS CONTEXT,
    'PAYMENT' AS CATEGORY,
    'SINGLE_PAYMENT' AS TYPE  ,
    DATA ,
    0 AS DATA_VERSION,
    CURRENT_TIMESTAMP AS TIMESTAMP,
    CURRENT_TIMESTAMP AS CREATED_ON,
    CURRENT_TIMESTAMP  AS MODIFIED_ON
FROM (
	SELECT 
		TDP.PAYMENT_ID,
		JSON_OBJECT
		(
			'paymentDate' VALUE tdp.POSTED_DATE
			,'effectiveDate' VALUE tdp.EFFECTIVE_DATE
			,'paymentAmount' VALUE tdp.PAYMENT_AMOUNT       
			,'transactionSource' VALUE 'ETL Migration'
			,'paymentMethod' VALUE TDP.PAYMENT_METHOD
			,'directed' VALUE 'TRUE'
			,'referenceId' VALUE TDP.PAYMENT_ID
			,'status' VALUE 'COMPLETED'
			,'customerId' VALUE tdp.CONSUMER_UUID
			,'responsiblePartyName' VALUE C.CUSTOMERNAME
			,'suffix' VALUE C.SUFFIX
			,'sourceSystem' VALUE 'Data Migration'
			,'payor' VALUE  C.CUSTOMERNAME
			,'billingAddress' VALUE ADR.ADDRESS
			,'migrationSourceId' VALUE tdp.MIG_SRC_TRAN_ID
			,'transactions' VALUE JSON_ARRAYAGG(TRN.TRAN_JSON  RETURNING CLOB )
        ) AS DATA
	FROM COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT tdp  
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER c 
		ON RAWTOHEX(c.UUID ) = UPPER(REPLACE (tdp.CONSUMER_UUID , '-', ''))
	INNER JOIN 
	(
		SELECT 
			tdt.PAYMENT_ID,
			JSON_OBJECT
			(
				'accountNum' VALUE a.ACCOUNTNUM, 
				'paymentAmount' VALUE tdp.PAYMENT_AMOUNT,
				'agentId' VALUE ( SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_  WHERE USERNAME = 'etlmigrationuser@finvi.com'),
				'clientDue' VALUE DUES.Due_Client,
				'agencyDue' VALUE DUES.Due_Agency,
				'contractName' VALUE ACO.ORGANIZATION_ID,
				'clientName' VALUE aco2.NAME,
				'trustAccountId' VALUE LOWER(REGEXP_REPLACE(ACO.TRUST_ACCOUNT_ID,'(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')),
				'subBalance' VALUE JSON_ARRAYAGG				
				(
					JSON_OBJECT
						( 
							'subBalanceCode' VALUE tdci.DESCRIPTION,
							'description' VALUE NULL ,
							'amount' VALUE TXN_AMT ,
							'contingencyFee' VALUE 0)
						) RETURNING CLOB
            )   AS TRAN_JSON 
            FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TRAN_HIST est
			INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_TRANSACTION tdt
				ON tdt.MIG_SRC_TRAN_ID = est.SOURCETRANSACTIONID 
				AND tdt.MIG_SRC_ACCT_ID = est.ACCOUNTID 
			INNER JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_PAYMENT tdp  
				ON tdt.PAYMENT_ID = tdp.PAYMENT_ID
			INNER JOIN  COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.ACCOUNT a
				ON TDT.MIG_SRC_ACCT_ID = a.MIGRATION_SOURCE_ID 
			INNER JOIN COM_FINVI_OASIS_CLIENTANDCREDITOR_{PP_TenantName}.AJ_CORE_ORGANIZATION aco
				ON ACO.UUID = A.CLIENTCONTRACTID 
			INNER JOIN COM_FINVI_OASIS_CLIENTANDCREDITOR_{PP_TenantName}.AJ_CORE_ORGANIZATION aco2
				ON aco2.ORGANIZATION_ID = aco.CLIENT_ID
			INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER c  
				ON RAWTOHEX(c.UUID ) = UPPER(REPLACE (tdp.CONSUMER_UUID , '-', ''))
			INNER JOIN  COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_CHARGE_ITEM tdci
				ON tdci.CHARGE_ITEM_ID = tdt.CHARGE_ITEM_ID
			LEFT JOIN (SELECT PAYMENT_ID , 
					SUM(CASE WHEN TYPE = 230 THEN TXN_AMT ELSE 0 END) AS Due_Client,
					SUM(CASE WHEN TYPE = 220 THEN TXN_AMT ELSE 0 END) AS Due_Agency
					FROM COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_TRANSACTION
					GROUP BY PAYMENT_ID 
				) DUES ON dues.PAYMENT_ID = tdt.PAYMENT_ID 
			WHERE tdt.PAYMENT_ID IS NOT NULL 
			AND tdt.REVERSES_TRANSACTION_ID IS NULL
			GROUP BY tdt.PAYMENT_ID, a.ACCOUNTNUM, tdp.PAYMENT_AMOUNT, c.CUSTOMERNAME, DUES.Due_Client, DUES.Due_Agency, ACO.ORGANIZATION_ID,ACO.TRUST_ACCOUNT_ID, aco2.NAME
	) TRN ON trn.PAYMENT_ID = tdp.PAYMENT_ID
	LEFT JOIN (SELECT CUSTOMERID,
			ADDRESS1 || ' ' || ADDRESS2 || ' ' || CITY || ' ' || POSTALCODE AS ADDRESS, 
			ROW_NUMBER () OVER (PARTITION BY CUSTOMERID ORDER BY LASTUPDATEDATE DESC) AS REC_NO
			FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMERCONTACTADDRESS 
		) ADR ON ADR.CUSTOMERID = C.CUSTOMERID AND REC_NO = 1
	GROUP BY 
		TDP.PAYMENT_ID
		, TDP.POSTED_DATE
		, TDP.EFFECTIVE_DATE
		, TDP.PAYMENT_AMOUNT
		, TDP.MIG_SRC_TRAN_ID
		, tdp.CONSUMER_UUID 			
		, C.CUSTOMERNAME
		, C.SUFFIX
		, TDP.PAYMENT_METHOD
		, TDP.PAYMENT_ID
		, ADR.ADDRESS
)