INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE_VALIDATION_INFO
(
	UUID ,
	RESPONSIBLE_ID ,
	VALIDATION_START_DATE,
	VALIDATION_METHOD, 
	VALIDATION_END_DATE,
	CREATEDON , 
	CREATEDBY ,
	MODIFIEDON , 
	MODIFIEDBY 
)
SELECT 
	SYS_GUID() UUID,
	RESPONSIBLE_ID,
	VALIDATION_START_DATE,
	'Letter' VALIDATION_METHOD,
	VALIDATION_END_DATE, 
	SYSTIMESTAMP CREATEDON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATEDBY,
	SYSTIMESTAMP MODIFIEDON, 
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIEDBY	
FROM 
	(
		SELECT 
			r2.ID RESPONSIBLE_ID, 
			L.STRATEGYDATE,
			L.STRATEGYDATE + vc.DELIVERY_DAYS VALIDATION_START_DATE,
			L.STRATEGYDATE + vc.DELIVERY_DAYS + vc.VALIDATION_PERIOD_WAIT_DAYS VALIDATION_END_DATE,
			RANK() OVER (PARTITION By l.responsibleid ORDER BY l.strategydate DESC) AS rnk
		FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.LETTERCHANNELACTUALRESULT l 
		INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLEINDEX r2 ON L.RESPONSIBLEID = R2.RESPONSIBLEID  
		INNER JOIN COM_FINVI_OASIS_RESTRICTIONS_{PP_TenantName}.VALIDATION_CONFIGURATION vc ON 1=1 AND VALIDATION_METHOD = 'Letter' 
		WHERE l.LETTERDATA9 = 'CFPBV' 
	) WHERE rnk = 1