INSERT INTO COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.SCORE_INFORMATION 
(
    ID,
    CREATED_BY,
    CREATED_ON,
    MODIFIED_BY,
    MODIFIED_ON,
    SCORE_TYPE,
    SCORE_VALUE,
    IMPORT_DATE,
    SOURCE,
    PARTNER_ID,
    RESPONSIBLE_ID,
    ACCOUNT_ID
)
SELECT
    SYS_GUID() AS ID,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY,
    SYSDATE AS CREATED_ON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,
    SYSDATE AS MODIFIED_ON,
    'I' AS SCORE_TYPE,
    I_SCORE AS SCORE_VALUE,
    SYSDATE AS IMPORT_DATE,
    'Vendor' AS SOURCE,
    '7e5ce78b-cd23-4ae2-ab7a-7c644b95a60e' AS PARTNER_ID,
    r.RESPONSIBLEID  AS RESPONSIBLE_ID,
    r.ACCOUNTNUM AS ACCOUNT_ID
FROM
    (
    SELECT
        ACCOUNTID,
        CONSUMERID,
        I_SCORE
    FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TIG_SCORES
    ) cte1
INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE r
ON cte1.ACCOUNTID = r.MIG_SRC_ACCT_ID 
   AND cte1.CONSUMERID = r.MIG_SRC_CONS_ID 
UNION ALL 
SELECT
    SYS_GUID() AS ID,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATED_BY,
    SYSDATE AS CREATED_ON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,
    SYSDATE AS MODIFIED_ON,
    'Z' AS SCORE_TYPE,
    Z_SCORE AS SCORE_VALUE,
    SYSDATE AS IMPORT_DATE,
    'Vendor' AS SOURCE,
    '7e5ce78b-cd23-4ae2-ab7a-7c644b95a60e' AS PARTNER_ID,
    r.RESPONSIBLEID AS RESPONSIBLE_ID,
     r.ACCOUNTNUM AS ACCOUNT_ID
 FROM
    (
    SELECT
        ACCOUNTID,
        CONSUMERID,
        Z_SCORE
    FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_TIG_SCORES
    ) cte2     
INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE r
  ON  cte2.ACCOUNTID = r.MIG_SRC_ACCT_ID 
 AND cte2.CONSUMERID = r.MIG_SRC_CONS_ID