INSERT INTO COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_CHARGE_ITEM 
(
	CREATE_DATE,
	MODIFIED_ON,
	CREATE_BY,
	MODIFIED_BY,
	ACCOUNT_ID,
	DESCRIPTION,
	CHARGE_AMOUNT,
	AMOUNT_PAID,
	TYPE_SCODE_UUID,
	TYPE_SCODE_ID,
	CURRENCY_ID,
	INTEREST_CURRENT_THRU,
	AMOUNT_ADJUSTED,
	POSTED_DATE,
	SYSTEM_GENERATED_CHARGE,
	ORIG_PLACEMENT_ITEM,
	POSTED_WITH_ACCOUNT,
	DATE_PLACED_OR_ADDED,
	AMOUNT_PAID_SINCE_JUDGMENT,
	AMOUNT_ADJUSTED_SINCE_JUDGMENT,
	AMOUNT_PAID_PRE_JUDGMENT,
	CHARGE_AMT_PRE_JUDG,
	CHARGE_AMT_POST_JUDG,
	SETTL_CONV_FEE_AMT_ADJUSTED,
	SETTL_CONV_FEE_AMT_PAID
)
SELECT
	SYSDATE AS CREATE_DATE,
	SYSDATE AS MODIFIED_ON,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATE_BY,
    (SELECT IDPUSERID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS MODIFIED_BY,	
	B.ACCOUNT_ID,
	SUB.CODE,
	STG.CHARGE_AMOUNT,
	STG.AMOUNT_PAID,
	LOWER(
	SUBSTR(SUB.UUID,1,8) || '-' ||
	SUBSTR(SUB.UUID,9,4) || '-' ||
	SUBSTR(SUB.UUID,13,4) || '-' ||
	SUBSTR(SUB.UUID,17,4) || '-' ||
	SUBSTR(SUB.UUID,21)) AS TYPE_SCODE_UUID,
	83 AS TYPE_SCODE_ID,
	171 AS CURRENCY_ID,
	SYSDATE AS INTEREST_CURRENT_THRU,
	STG.AMOUNT_ADJUSTED,
	SYSDATE AS POSTED_DATE,
	0 AS SYSTEM_GENERATED_CHARGE,
	1 AS ORIG_PLACEMENT_ITEM,
	0 AS POSTED_WITH_ACCOUNT,
	SYSDATE AS DATE_PLACED_OR_ADDED,
	0 AS AMOUNT_PAID_SINCE_JUDGMENT,
	0 AS AMOUNT_ADJUSTED_SINCE_JUDGMENT,
	0 AS AMOUNT_PAID_PRE_JUDGMENT,
	0 AS CHARGE_AMT_PRE_JUDG,
	0 AS CHARGE_AMT_POST_JUDG,
	0 AS SETTL_CONV_FEE_AMT_ADJUSTED,
	0 AS SETTL_CONV_FEE_AMT_PAID
FROM 
	(
		SELECT 
			'PRN' AS CODE, 
			NVL(PRN_INITIALBALANCE,0) AS CHARGE_AMOUNT, 
			CASE WHEN NVL(PRN_INITIALBALANCE,0) >= NVL(PRN_CURRENTBALANCE,0) 
				THEN (NVL(PRN_INITIALBALANCE,0) - NVL(PRN_CURRENTBALANCE,0)) 
				ELSE 0 
			END AS AMOUNT_PAID,
			CASE WHEN NVL(PRN_INITIALBALANCE,0) < NVL(PRN_CURRENTBALANCE,0) 
				THEN (NVL(PRN_CURRENTBALANCE,0) - NVL(PRN_INITIALBALANCE,0)) 
				ELSE 0 
			END AS AMOUNT_ADJUSTED,
			ACCOUNTID
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCT_BAL_INFO
		UNION ALL
		SELECT 
			'INT' AS CODE, 
			NVL(INT_INITIALBALANCE,0) AS CHARGE_AMOUNT, 
			CASE WHEN NVL(INT_INITIALBALANCE,0) >= NVL(INT_CURRENTBALANCE,0) 
				THEN (NVL(INT_INITIALBALANCE,0) - NVL(INT_CURRENTBALANCE,0)) 
				ELSE 0 
			END AS AMOUNT_PAID,
			CASE WHEN NVL(INT_INITIALBALANCE,0) < NVL(INT_CURRENTBALANCE,0) 
				THEN (NVL(INT_CURRENTBALANCE,0) - NVL(INT_INITIALBALANCE,0)) 
				ELSE 0 
			END AS AMOUNT_ADJUSTED,			
			ACCOUNTID
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCT_BAL_INFO
		UNION ALL
		SELECT 
			'LI3' AS CODE, 
			NVL(LI3_INITIALBALANCE,0) AS CHARGE_AMOUNT, 
			CASE WHEN NVL(LI3_INITIALBALANCE,0) >= NVL(LI3_CURRENTBALANCE,0) 
				THEN (NVL(LI3_INITIALBALANCE,0) - NVL(LI3_CURRENTBALANCE,0)) 
				ELSE 0 
			END AS AMOUNT_PAID,
			CASE WHEN NVL(LI3_INITIALBALANCE,0) < NVL(LI3_CURRENTBALANCE,0) 
				THEN (NVL(LI3_CURRENTBALANCE,0) - NVL(LI3_INITIALBALANCE,0)) 
				ELSE 0 
			END AS AMOUNT_ADJUSTED,			
			ACCOUNTID
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCT_BAL_INFO
		UNION ALL
		SELECT 
			'LI4' AS CODE, NVL(LI4_INITIALBALANCE,0) AS CHARGE_AMOUNT,
			CASE WHEN NVL(LI4_INITIALBALANCE,0) >= NVL(LI4_CURRENTBALANCE,0) 
				THEN (NVL(LI4_INITIALBALANCE,0) - NVL(LI4_CURRENTBALANCE,0)) 
				ELSE 0 
			END AS AMOUNT_PAID,
			CASE WHEN NVL(LI4_INITIALBALANCE,0) < NVL(LI4_CURRENTBALANCE,0) 
				THEN (NVL(LI4_CURRENTBALANCE,0) - NVL(LI4_INITIALBALANCE,0)) 
				ELSE 0 
			END AS AMOUNT_ADJUSTED,			
			ACCOUNTID			
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCT_BAL_INFO
		UNION ALL
		SELECT 
			'AIN' AS CODE, 
			0 AS CHARGE_AMOUNT, 
			0 AS AMOUNT_PAID,
			NVL(AIN_CURRENTBALANCE,0) AS AMOUNT_ADJUSTED, 
			ACCOUNTID
		FROM ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_ACCT_BAL_INFO
	) stg 
JOIN COM_FINVI_OASIS_MACRO_ACCOUNT_{PP_TenantName}.T_DATA_ACCOUNT b  
	ON stg.ACCOUNTID = b.MIG_SRC_ACCT_ID
JOIN COM_FINVI_OASIS_SUBBALANCES_{PP_TenantName}.AJ_CORE_SUBBALANCE_TYPE sub
	ON sub.code =  stg.code
ORDER BY b.account_id