INSERT INTO  COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMERCONTACTPHONE
(
	UUID,
	PHONENUM,
	EXPRESSCONSENTVOICE,
	EXPRESSCONSENT,
	ESIGNSMSCONSENT,
	LASTEXPRESSCONSENTVOICEUPDATEDATE,
	EXPRESSCONSENTSMS,
	LASTEXPRESSCONSENTSMSUPDATEDATE,
	EXPRESSCONSENTAIVOICE,
	LASTEXPRESSCONSENTAIVOICEUPDATEDATE,
	EXPRESSCONSENTPRERECORDEDMESSAGE,
	LASTEXPRESSCONSENTPRERECORDEDMESSAGEUPDATEDATE,
	CUSTOMERID,
	STATUS,
	TYPEID,
	CREATEDATE,
	LASTUPDATEDATE,
	CREATORID,
	LASTUPDATERID,
	SOURCE,
	HISTORICAL,
	ISDEFAULT,
	UPDATED,
	SOURCEREFERENCEID,
	PHONETYPEREFERENCEID
)
SELECT
    SYS_GUID() AS UUID,
    REGEXP_REPLACE(esppi.ARPHPHONE, '[^0-9]', '') AS PHONENUM,
    'NA' AS EXPRESSCONSENTVOICE,
    'NA' AS EXPRESSCONSENT,
	'NA' AS ESIGNSMSCONSENT,
	ARPHCALLCONSENTDATE + 0.5 AS LASTEXPRESSCONSENTVOICEUPDATEDATE,
	'NA' AS EXPRESSCONSENTSMS,
	ARPHSMSCONSENTDATE + 0.5 AS LASTEXPRESSCONSENTSMSUPDATEDATE,
	'NA' AS EXPRESSCONSENTAIVOICE,
    ARPHARTIFICIALVOICECONSENTDATE + 0.5  AS LASTEXPRESSCONSENTAIVOICEUPDATEDATE,
	'NA' AS EXPRESSCONSENTPRERECORDEDMESSAGE,
	ARPHPRERECORDEDMSGCONSENTDATE + 0.5  AS LASTEXPRESSCONSENTPRERECORDEDMESSAGEUPDATEDATE,
    c.CUSTOMERID,
    esppi.ARPHPHONESTATUS AS STATUS,
    pt.PRIORITY AS TYPEID,
    SYSDATE AS CREATEDATE,
    SYSDATE AS LASTUPDATEDATE,
    (SELECT ID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS CREATORID,
    (SELECT ID FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.user_ WHERE USERNAME = 'etlmigrationuser@finvi.com') AS LASTUPDATERID,
    --'CLIENT' AS SOURCE,
    --(select SOURCE FROM COM_FINVI_OASIS_static_data_{PP_TenantName}.demographic_source WHERE SOURCE='Client') AS SOURCE,
    --UPPER(ds."SOURCE"),
	CASE
		WHEN esppi.ARPHTYPE = 'Mobile' AND esppi.ARPHMAPKEY = 'SECONDARY' THEN 'CLIENT' 
		WHEN esppi.ARPHTYPE = 'Home' THEN 'CLIENT'
		ELSE 'VENDOR'
	END AS SOURCE,
	--CASE WHEN esppi.ISPRIMARY='Y' THEN 'N' ELSE 'Y' END AS HISTORICAL,
   	'N' AS HISTORICAL,
    esppi.ISPRIMARY AS ISDEFAULT,
    'N' AS UPDATED,
    --(select ID FROM COM_FINVI_OASIS_static_data_{PP_TenantName}.demographic_source WHERE SOURCE='Client') AS SOURCEREFERENCEID,
    ds.ID AS SOURCEREFERENCEID,
    --(SELECT pt.ID FROM COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.PHONE_TYPE pt WHERE pt.NAME = 'Home') AS PHONETYPEREFERENCEID
    pt.ID AS PHONETYPEREFERENCEID
FROM  
    ETL_OASIS_DATA_MIG_{PP_TenantName}.ETL_STG_PRTY_PHONE_INFO esppi
    INNER JOIN COM_FINVI_OASIS_static_data_{PP_TenantName}.demographic_source ds ON 
    	(CASE
	    	WHEN esppi.ARPHTYPE = 'Mobile' AND esppi.ARPHMAPKEY = 'SECONDARY' THEN 'CLIENT' 
			WHEN esppi.ARPHTYPE = 'Home' THEN 'CLIENT'
			ELSE 'VENDOR'
		END) = upper(ds.SOURCE)
    INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.CUSTOMER c ON c.MIGRATION_SOURCE_ID = esppi.CONSUMERID
    LEFT JOIN COM_FINVI_OASIS_STATIC_DATA_{PP_TenantName}.PHONE_TYPE pt ON UPPER(pt.NAME) = UPPER(esppi.ARPHTYPE)
WHERE 
	REGEXP_REPLACE(esppi.ARPHPHONE, '[^0-9]', '') IS NOT NULL 
	AND LENGTH(REGEXP_REPLACE(esppi.ARPHPHONE, '[^0-9]', '')) >= 10
--	AND ds."SOURCE" = 'Client'