UPDATE COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE
SET HASVALIDATIONLETTERSENT = 1, HASVALIDATIONCOMMUNICATIONSENT = 1
WHERE RESPONSIBLEID  IN 
(
	SELECT 
		R.RESPONSIBLEID 
	FROM COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLE_VALIDATION_INFO rvi 
	INNER JOIN COM_FINVI_OASIS_ACCOUNT_{PP_TenantName}.RESPONSIBLEINDEX r ON r.ID = rvi.RESPONSIBLE_ID 
)